import { fetchApi } from '@/http'
import type { IntegratedMonitoringSnapshot } from './integratedMonitoring.types'

const API_MODE = import.meta.env.VITE_API_MODE || 'mock'

export const mockIntegratedSnapshot: IntegratedMonitoringSnapshot = {
    generatedAt: new Date().toISOString(),
    counts: {
        total: 7,
        online: 6,
        stale: 1,
        offline: 0,
        work: 4,
        surveillance: 3,
    },
    maps: [
        {
            id: 1,
            code: 'MAP-SITE-01',
            name: 'KORAD 시설 종합 배치도 (Site Map)',
            width: 1600,
            height: 800,
            imageUrl: '/sample_map/site_map.svg',
            resolution: 0.05,
            origin_x: 0,
            origin_y: 0,
            robots: [],
        },
        {
            id: 2,
            code: 'MAP-INDOOR-01',
            name: 'ZONE A : 처분용기 장입 실내 1층 도면',
            width: 1400,
            height: 800,
            imageUrl: '/sample_map/indoor_disposal_map.svg',
            resolution: 0.05,
            origin_x: 0,
            origin_y: 0,
            robots: [],
        },
        {
            id: 3,
            code: 'MAP-OUTDOOR-01',
            name: 'ZONE C : 외곽 시설물 정밀 순찰 2D 지도',
            width: 1600,
            height: 500,
            imageUrl: '/sample_map/outdoor_patrol_map.svg',
            resolution: 0.1,
            origin_x: 0,
            origin_y: 0,
            robots: [],
        },
        {
            id: 4,
            code: 'MAP-INDOOR-02',
            name: 'ZONE B : 방사성 폐기물 인수검사동 2D 도면',
            width: 1400,
            height: 800,
            imageUrl: '/sample_map/inspection_building_map.svg',
            resolution: 0.05,
            origin_x: 0,
            origin_y: 0,
            robots: [],
        },
    ],
    robots: [
        {
            id: 1,
            name: '무인지게차 1호기',
            robotType: 'WORK',
            mapId: 2,
            batteryPercent: 88,
            x: 12.5,
            y: 8.2,
            siteX: 16.0,
            siteY: 10.0,
            heading: 90,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
        {
            id: 2,
            name: '저상형 AMR 1호기',
            robotType: 'WORK',
            mapId: 2,
            batteryPercent: 92,
            x: 18.0,
            y: 8.2,
            siteX: 24.0,
            siteY: 10.0,
            heading: 0,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
        {
            id: 3,
            name: '저상형 AMR 2호기',
            robotType: 'WORK',
            mapId: 2,
            batteryPercent: 75,
            x: 5.0,
            y: 3.5,
            siteX: 8.0,
            siteY: 18.0,
            heading: 270,
            communicationStatus: 'ONLINE',
            status: 'IDLE',
        },
        {
            id: 4,
            name: '산업용 장입 로봇 1호기',
            robotType: 'WORK',
            mapId: 4,
            batteryPercent: 100,
            x: 25.4,
            y: 15.6,
            siteX: 78.0,
            siteY: 14.0,
            heading: 180,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
        {
            id: 5,
            name: '편심 자율주행 로봇 1호기',
            robotType: 'SURVEILLANCE',
            mapId: 3,
            batteryPercent: 64,
            x: 32.0,
            y: 20.5,
            siteX: 32.0,
            siteY: 38.0,
            heading: 45,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
        {
            id: 6,
            name: '4족 보행 로봇 1호기 (Spot)',
            robotType: 'SURVEILLANCE',
            mapId: 3,
            batteryPercent: 82,
            x: 45.0,
            y: 30.0,
            siteX: 60.0,
            siteY: 38.0,
            heading: 90,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
        {
            id: 7,
            name: '실외 자율주행 로봇 1호기',
            robotType: 'SURVEILLANCE',
            mapId: 3,
            batteryPercent: 95,
            x: 60.0,
            y: 12.0,
            siteX: 88.0,
            siteY: 38.0,
            heading: 180,
            communicationStatus: 'ONLINE',
            status: 'RUNNING',
        },
    ],
}

export const getIntegratedMonitoring = async () => {
    if (API_MODE === 'mock') {
        return { data: mockIntegratedSnapshot, result: 'SUCCESS', resultMessage: '성공' }
    }
    try {
        return await fetchApi().get<IntegratedMonitoringSnapshot>('/api/v1/monitoring/integrated')
    } catch {
        return { data: mockIntegratedSnapshot, result: 'SUCCESS', resultMessage: '성공' }
    }
}
